### ISSUE TITLE
tabName parameter is not used for name of the tab

### ISSUE THREAD

**Issue by ShikunovDmitry** [mclay/azure-pipeline-allure-report#15]
Hello Michael!
Thank you for your extension.

I faced an issue with using tabName parameter.

I passed a custom name in parameter, however it wasn't used for tab name

Here is how I use the task

```
  - task: PublishAllureReport@1
        displayName: 'Publish Allure Report ${{ parameters.activeProfile }} tab'
        inputs:
          reportDir: '${{ parameters.workingDirectory }}/build/reports/allure-report/allureReport'
          tabName: 'Test result ${{ parameters.activeProfile }}'
```

But it has "Allure Report" tab name in result. 
There are no any issues during report generation.

Thanks
